# Data params
input_dir: /global/cscratch1/sd/danieltm/ExaTrkX/top_tagging/raw_input/
data_split: [4000,1000]

# Training params
n_epochs: 30
lr: 0.0001
factor: 0.3
patience: 10
warmup: 800
train_batch: 10
val_batch: 10

# Model params
input_feature_dim: 1
message_dim: 128
output_feature_dim: 1
edge_feature_dim: 0
n_layers: 4
activation: SiLU