# Data params
input_dir: /global/cscratch1/sd/danieltm/ExaTrkX/top_tagging/raw_input/
data_split: [200000,10000,5]

# Training params
n_epochs: 40
lr: 0.003
factor: 0.3
patience: 20
warmup: 500
train_batch: 400
val_batch: 400
dropout: 0.1
signal_goal: 0.3 # The efficiency goal for the signal jets

# Model params
input_coords_dim: 7
message_dim: [64, 128, 256]
output_feature_dim: 1
nb_layers: 3
activation: ReLU
batch_norm: True
k: 16
r: 1
graph_construction: dynamic_knn
equivariant: False
features: [delta_eta, delta_phi, log_pt, log_E, delta_pt, delta_E, delta_R]
coordinates: [delta_eta, delta_phi]
