# Data params
input_dir: /global/cscratch1/sd/danieltm/ExaTrkX/top_tagging/raw_input/
data_split: [200000, 10000, 1]
project: GeneralNet

# Training params
max_epochs: 50
lr: 0.001
factor: 0.3
patience: 20
warmup: 500
train_batch: 100
val_batch: 100
dropout: 0.1
signal_goal: 0.3 # The efficiency goal for the signal jets

# Equivariance params
equivariant: True
vector: x
scalars: #[delta_eta, delta_phi, log_pt, log_E, delta_pt, delta_E, delta_R]

# Model params
scalar_dim: 1
vector_dim: 4
invariant_vector_dim: 1
message_dim: [16]
final_dim: 256
nb_edge_layers: 3
nb_node_layers: 0
output_feature_dim: 1
n_graph_iters: 3
concat_output: True
activation: ReLU
batch_norm: True
layer_norm: True
k: 16
r: 0.1
graph_construction: fully_connected
