wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.9
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.7
activation:
  desc: null
  value: SiLU
data_split:
  desc: null
  value:
  - 1000
  - 100
edge_feature_dim:
  desc: null
  value: 0
factor:
  desc: null
  value: 0.3
input_dir:
  desc: null
  value: /global/cscratch1/sd/danieltm/ExaTrkX/top_tagging/raw_input/
input_feature_dim:
  desc: null
  value: 1
lr:
  desc: null
  value: 0.0001
message_dim:
  desc: null
  value: 64
n_epochs:
  desc: null
  value: 30
n_layers:
  desc: null
  value: 6
output_feature_dim:
  desc: null
  value: 2
patience:
  desc: null
  value: 10
warmup:
  desc: null
  value: 1000
