# Dataset
program: train.py
method: bayes
project: GeneralNet
metric:
    name: auc.max
    goal: maximize
parameters:
    # Model hyperparameters
    equivariant:
        values: [False]
    nb_edge_layers:
        min: 1
        max: 3
    nb_node_layers:
        min: 0
        max: 3
    nb_graph_iters:
        min: 1
        max: 6
    message_dim:
        min: 8
        max: 512
    shortcut:
        values: [skip, concat, none]
    activation:
        values: [ReLU, SiLU, Tanh]
    batch_norm:
        values: [False, True]
    layer_norm:
        values: [False, True]
    k:
        min: 3
        max: 32        
    dropout:
        min: 0.01
        max: 0.4
    
    # Training hyperparameters
    lr: 
        min: 0.00001
        max: 0.01
    patience: 
        min: 1
        max: 25
    factor: 
        min: 0.1
        max: 0.9
    max_epochs:
        min: 10
        max: 50