# Data params
project: LorentzNet
input_dir: /global/cscratch1/sd/danieltm/ExaTrkX/top_tagging/raw_input/
data_split: [[2000,200]]

# Training params
max_epochs: 30
lr: [0.001, 0.0001, 0.00001]
factor: 0.3
patience: 10
warmup: 4000

# Model params
input_feature_dim: 1
message_dim: [16, 32, 64, 128]
output_feature_dim: 2
edge_feature_dim: 0
n_layers: [2, 4, 6]
activation: SiLU

# Callbacks
callbacks: