# Data params
input_dir: /global/cscratch1/sd/danieltm/ExaTrkX/top_tagging/raw_input/
data_split: [[200000,20000,20000]]
project: GeneralNet

# Training params
max_epochs: 24
lr: 0.003
factor: 0.75
patience: 1
warmup: 4000
train_batch: 400
val_batch: 4000
dropout: 0.1
signal_goal: 0.3 # The efficiency goal for the signal jets

# Equivariance params
equivariant: False
vector: x
scalars: [[delta_eta, delta_phi, log_pt, log_E, delta_pt, delta_E, delta_R]]

# Model params
scalar_dim: 1
vector_dim: 4
invariant_vector_dim: 1
message_dim: [[64, 128, 256]]
final_dim: 256
nb_edge_layers: 3
nb_node_layers: 0
output_feature_dim: 1
n_graph_iters: 3
shortcut: skip
activation: ReLU
batch_norm: True
layer_norm: True
k: 16
r: 0.1
graph_construction: dynamic_knn

callbacks: 
